### ISSUE TITLE
segment when cufflinks with -mask-file

### ISSUE THREAD

**Issue by wangyugui** [cole-trapnell-lab/cufflinks#95]
Hi.

segment when cufflinks with -mask-file

```
(gdb) where
#6  0x00007ff7680e0d4d in rewind () from /lib64/libc.so.6
#7  0x00000000005430be in read_transcripts (f=f@entry=0xd89770, seqdata=..., crc_result=..., keepAttrs=keepAttrs@entry=true)
    at gtf_tracking.cpp:595
#8  0x00000000004a14ab in load_ref_rnas (ref_mRNA_file=ref_mRNA_file@entry=0xd89770, rt=...,
    ref_mRNAs=std::vector of length 0, capacity 1024, gtf_crc_result=..., loadSeqs=loadSeqs@entry=false, loadFPKM=loadFPKM@entry=false)
    at bundles.cpp:104
#9  0x000000000041621b in driver (hit_file_name="/biowrk/rna-benchmark/gtf.links.GRCh38.p11/TCM/merge.bam", ref_gtf=<optimized out>,
    ref_gtf@entry=0xd89530, mask_gtf=mask_gtf@entry=0xd89770) at cufflinks.cpp:1700
#10 0x000000000040f1f7 in main (argc=23, argv=0x7ffcd3f9a3c8) at cufflinks.cpp:1797
```

**Comment by wangyugui** [comment]
I worked around this problem by mask the bam file by samtools.

```
samtools view -L ${ref_dir}/cufflinks.mask.bed -u -o mask.bam -U cufflink.bam my.bam
```
